# Generated by Django 3.0.5 on 2020-12-02 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appvisual', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='X_axis_Data',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='Y_axis_Data',
        ),
    ]
